/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package counsellingsystem;
import database.MySqlConnect;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rachna
 */
public class AdminMainPage extends javax.swing.JFrame {
    Connection con ;
    Statement stmt;
    ResultSet rs;
    /**
     * Creates new form AdminMainPage
     */
        public AdminMainPage(String user_name){
            initComponents();
        try{    
        String adminUserid = " ADMIN : " + user_name;
        adminLabel.setText(adminUserid);
        admin_panel.setVisible(false);
        
    }
        catch(Exception e2){
            e2.printStackTrace();
        }}

    //private void initComponents() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    
    AdminMainPage(){
        System.out.println("Admin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome_panel = new javax.swing.JPanel();
        adminLabel = new javax.swing.JLabel();
        logout_btn = new javax.swing.JButton();
        list_panel = new javax.swing.JPanel();
        rank_list_btn = new javax.swing.JButton();
        college_list_btn = new javax.swing.JButton();
        new_admin_btn = new javax.swing.JButton();
        remove_admin_btn = new javax.swing.JButton();
        get_allotment_btn = new javax.swing.JButton();
        regstudent_list_btn = new javax.swing.JButton();
        admin_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        last_name = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        repassword = new javax.swing.JPasswordField();
        create_btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(275, 150));
        setPreferredSize(new java.awt.Dimension(675, 600));

        welcome_panel.setBackground(new java.awt.Color(255, 255, 255));
        welcome_panel.setMinimumSize(new java.awt.Dimension(650, 500));
        welcome_panel.setOpaque(false);
        welcome_panel.setPreferredSize(new java.awt.Dimension(675, 550));

        adminLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        adminLabel.setText("WELCOME  :");

        logout_btn.setBackground(new java.awt.Color(255, 255, 255));
        logout_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logout_btn.setText("Logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        list_panel.setBackground(new java.awt.Color(255, 255, 255));

        rank_list_btn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        rank_list_btn.setText("Rank List");
        rank_list_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rank_list_btnActionPerformed(evt);
            }
        });

        college_list_btn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        college_list_btn.setText("List of Colleges");
        college_list_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                college_list_btnActionPerformed(evt);
            }
        });

        new_admin_btn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        new_admin_btn.setText("Create New Admin");
        new_admin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_admin_btnActionPerformed(evt);
            }
        });

        remove_admin_btn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        remove_admin_btn.setText("Remove Admin");
        remove_admin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_admin_btnActionPerformed(evt);
            }
        });

        get_allotment_btn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        get_allotment_btn.setText("Get Allotment");
        get_allotment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_allotment_btnActionPerformed(evt);
            }
        });

        regstudent_list_btn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        regstudent_list_btn.setText("Registered Students");
        regstudent_list_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regstudent_list_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout list_panelLayout = new javax.swing.GroupLayout(list_panel);
        list_panel.setLayout(list_panelLayout);
        list_panelLayout.setHorizontalGroup(
            list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, list_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regstudent_list_btn)
                    .addComponent(get_allotment_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rank_list_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_admin_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(college_list_btn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(remove_admin_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        list_panelLayout.setVerticalGroup(
            list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_panelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rank_list_btn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(regstudent_list_btn)
                        .addComponent(college_list_btn)))
                .addGap(12, 12, 12)
                .addGroup(list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_admin_btn)
                    .addComponent(get_allotment_btn)
                    .addComponent(remove_admin_btn))
                .addContainerGap())
        );

        javax.swing.GroupLayout welcome_panelLayout = new javax.swing.GroupLayout(welcome_panel);
        welcome_panel.setLayout(welcome_panelLayout);
        welcome_panelLayout.setHorizontalGroup(
            welcome_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcome_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminLabel)
                .addGap(148, 148, 148)
                .addComponent(logout_btn)
                .addContainerGap())
            .addGroup(welcome_panelLayout.createSequentialGroup()
                .addComponent(list_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        welcome_panelLayout.setVerticalGroup(
            welcome_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcome_panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(welcome_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminLabel)
                    .addComponent(logout_btn))
                .addGap(18, 18, 18)
                .addComponent(list_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        admin_panel.setBackground(new java.awt.Color(255, 255, 255));
        admin_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "New Admin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe Print", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("          User-ID       :  ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("       First Name     : ");

        user_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        user_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_idActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("      Last Name       : ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("        Password       :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Re-enter Password  :");

        first_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        first_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_nameActionPerformed(evt);
            }
        });

        last_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_nameActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        repassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        repassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repasswordActionPerformed(evt);
            }
        });

        create_btn.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        create_btn.setText("Create");
        create_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout admin_panelLayout = new javax.swing.GroupLayout(admin_panel);
        admin_panel.setLayout(admin_panelLayout);
        admin_panelLayout.setHorizontalGroup(
            admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(first_name, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(last_name)
                    .addComponent(password)
                    .addComponent(repassword)
                    .addComponent(user_id))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(admin_panelLayout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(create_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        admin_panelLayout.setVerticalGroup(
            admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_panelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(17, 17, 17)
                .addGroup(admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(first_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(repassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(create_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(admin_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(welcome_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(welcome_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        new Counseling_system().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_logout_btnActionPerformed

    private void regstudent_list_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regstudent_list_btnActionPerformed
        Reg_Students obj = new Reg_Students();
        obj.setLayout();
    }//GEN-LAST:event_regstudent_list_btnActionPerformed

    private void rank_list_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rank_list_btnActionPerformed
        new Enter_mark().setVisible(false);
        Get_rank r = new Get_rank();
        r.setVisible(true);
    }//GEN-LAST:event_rank_list_btnActionPerformed

    private void college_list_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_college_list_btnActionPerformed
        new Colleges_list().setVisible(true);
    }//GEN-LAST:event_college_list_btnActionPerformed

    private void get_allotment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_allotment_btnActionPerformed
        Allotment_Class ac = new Allotment_Class();
        new Colleges_in_allotment().setVisible(true);
    }//GEN-LAST:event_get_allotment_btnActionPerformed

    private void new_admin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_admin_btnActionPerformed
        admin_panel.setVisible(true);
        //createnewadmin();
    }//GEN-LAST:event_new_admin_btnActionPerformed

    private void user_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_idActionPerformed
        createnewadmin();
    }//GEN-LAST:event_user_idActionPerformed

    private void first_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_nameActionPerformed
        //createnewadmin();
    }//GEN-LAST:event_first_nameActionPerformed

    private void last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_nameActionPerformed
        //createnewadmin();
    }//GEN-LAST:event_last_nameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        //createnewadmin();
    }//GEN-LAST:event_passwordActionPerformed

    private void repasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repasswordActionPerformed
        //createnewadmin();
    }//GEN-LAST:event_repasswordActionPerformed

    private void create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_btnActionPerformed
        createnewadmin();
    }//GEN-LAST:event_create_btnActionPerformed

    private void remove_admin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_admin_btnActionPerformed
        new remove_admin().setVisible(true);
    }//GEN-LAST:event_remove_admin_btnActionPerformed
     public boolean createnewadmin(){
        String pwd = password.getText();
        String repwd = repassword.getText();
        MySqlConnect sqlcon = new MySqlConnect();
        sqlcon.Connect();
        if(!pwd.equals(repwd)){
            JOptionPane.showMessageDialog(this, "The passwords do not match", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            String username = user_id.getText();
            if(username.equals("")){
                JOptionPane.showMessageDialog(this, "Enter a valid username", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else if(sqlcon.search_adminusername(username)){
                String f_name = first_name.getText();
                String l_name = last_name.getText();
                sqlcon.createnewad(username, pwd, f_name, l_name);
                JOptionPane.showMessageDialog(this, "New admin Created.", "Message", JOptionPane.INFORMATION_MESSAGE);
                admin_panel.setVisible(false);
            }
            else{
               JOptionPane.showMessageDialog(this, "This username already exists.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
      return false;  
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLabel;
    private javax.swing.JPanel admin_panel;
    private javax.swing.JButton college_list_btn;
    private javax.swing.JButton create_btn;
    private javax.swing.JTextField first_name;
    private javax.swing.JButton get_allotment_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField last_name;
    private javax.swing.JPanel list_panel;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton new_admin_btn;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton rank_list_btn;
    private javax.swing.JButton regstudent_list_btn;
    private javax.swing.JButton remove_admin_btn;
    private javax.swing.JPasswordField repassword;
    private javax.swing.JTextField user_id;
    private javax.swing.JPanel welcome_panel;
    // End of variables declaration//GEN-END:variables
}
