/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package counsellingsystem;

/**
 *
 * @author Rachna
 */
public class Colleges_in_allotment extends javax.swing.JFrame {

    /**
     * Creates new form Colleges_in_allotment
     */
    public Colleges_in_allotment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GMCC1 = new javax.swing.JButton();
        GMCT1 = new javax.swing.JButton();
        GMCT2 = new javax.swing.JButton();
        GMCK2 = new javax.swing.JButton();
        GMCK1 = new javax.swing.JButton();
        allotment_list = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();

        setLocation(new java.awt.Point(250, 175));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Allotment", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe Print", 0, 14))); // NOI18N

        GMCC1.setBackground(new java.awt.Color(255, 255, 255));
        GMCC1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        GMCC1.setText("Government Medical College, Calicut ");
        GMCC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GMCC1ActionPerformed(evt);
            }
        });

        GMCT1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        GMCT1.setText("Government Medical College, Trivandrum");
        GMCT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GMCT1ActionPerformed(evt);
            }
        });

        GMCT2.setBackground(new java.awt.Color(255, 255, 255));
        GMCT2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        GMCT2.setText("Government Medical College, Thrissur");
        GMCT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GMCT2ActionPerformed(evt);
            }
        });

        GMCK2.setBackground(new java.awt.Color(255, 255, 255));
        GMCK2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        GMCK2.setText("Government Medical College, Kottayam");
        GMCK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GMCK2ActionPerformed(evt);
            }
        });

        GMCK1.setBackground(new java.awt.Color(255, 255, 255));
        GMCK1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        GMCK1.setText("Government Medical College, Kannur");
        GMCK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GMCK1ActionPerformed(evt);
            }
        });

        allotment_list.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        allotment_list.setText("Final Allotment List");
        allotment_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allotment_listActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        back_btn.setText("<- Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(back_btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GMCC1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(GMCK2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GMCT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GMCT2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GMCK1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(allotment_list)))
                .addGap(132, 144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(back_btn)
                .addGap(29, 29, 29)
                .addComponent(GMCC1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GMCT1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GMCT2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(GMCK2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GMCK1)
                .addGap(26, 26, 26)
                .addComponent(allotment_list)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allotment_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allotment_listActionPerformed
        new Allotment().setVisible(true);
    }//GEN-LAST:event_allotment_listActionPerformed

    private void GMCC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GMCC1ActionPerformed
        new GMCC1().setVisible(true);
    }//GEN-LAST:event_GMCC1ActionPerformed

    private void GMCT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GMCT1ActionPerformed
        new GMCT1().setVisible(true);
    }//GEN-LAST:event_GMCT1ActionPerformed

    private void GMCT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GMCT2ActionPerformed
        new GMCT2().setVisible(true);
    }//GEN-LAST:event_GMCT2ActionPerformed

    private void GMCK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GMCK2ActionPerformed
        new GMCK2().setVisible(true);
    }//GEN-LAST:event_GMCK2ActionPerformed

    private void GMCK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GMCK1ActionPerformed
        new GMCK1().setVisible(true);
    }//GEN-LAST:event_GMCK1ActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
       this.setVisible(false);
       this.dispose(); 
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colleges_in_allotment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colleges_in_allotment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colleges_in_allotment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colleges_in_allotment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colleges_in_allotment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GMCC1;
    private javax.swing.JButton GMCK1;
    private javax.swing.JButton GMCK2;
    private javax.swing.JButton GMCT1;
    private javax.swing.JButton GMCT2;
    private javax.swing.JButton allotment_list;
    private javax.swing.JButton back_btn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
