/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package counsellingsystem;
import database.MySqlConnect;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Rachna
 */
public class Enter_mark extends javax.swing.JFrame {
    Connection con;
    ResultSet rs, rs1;
    Statement stmt;
    MySqlConnect sqlcon = new MySqlConnect();
    String uid;
    public void connect(){ 
    try
	{
            Class.forName("com.mysql.jdbc.Driver"); 
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project1?autoReconnect=true&useSSL=false", "root","rachna");
            stmt = con.createStatement();
	}
	catch(SQLException e1)
	{ 
            e1.printStackTrace();
        }
        catch(ClassNotFoundException e2){
            e2.printStackTrace();
        }
    }
    /**
     * Creates new form Enter_mark
     */
    public Enter_mark(String s) {
        initComponents();
        enter_mark_panel.setVisible(false);
        uid = s;
    }
    public Enter_mark(){
        System.out.println("Check Rank");
    }
    public void get_erank(String u_id){
       uid = u_id; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        enter_rank_label = new javax.swing.JLabel();
        get_rank_field = new javax.swing.JTextField();
        rank_submit_btn = new javax.swing.JButton();
        enter_mark_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        phy_mark_field = new javax.swing.JTextField();
        chem_mark_field = new javax.swing.JTextField();
        bio_mark_field = new javax.swing.JTextField();
        check_marks_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(275, 175));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        enter_rank_label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        enter_rank_label.setText("Enter your rank : ");

        get_rank_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_rank_fieldActionPerformed(evt);
            }
        });

        rank_submit_btn.setBackground(new java.awt.Color(255, 255, 255));
        rank_submit_btn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        rank_submit_btn.setText("Submit");
        rank_submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rank_submit_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(enter_rank_label)
                        .addGap(61, 61, 61)
                        .addComponent(get_rank_field, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(rank_submit_btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter_rank_label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(get_rank_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(rank_submit_btn)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        enter_mark_panel.setBackground(new java.awt.Color(255, 255, 255));
        enter_mark_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Enter Marks", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe Print", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Physics       :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Chemistry  :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Biology       :");

        phy_mark_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phy_mark_fieldActionPerformed(evt);
            }
        });

        bio_mark_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bio_mark_fieldActionPerformed(evt);
            }
        });

        check_marks_btn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        check_marks_btn.setText("Submit");
        check_marks_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_marks_btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Enter your physics, chemistry and biology marks");

        javax.swing.GroupLayout enter_mark_panelLayout = new javax.swing.GroupLayout(enter_mark_panel);
        enter_mark_panel.setLayout(enter_mark_panelLayout);
        enter_mark_panelLayout.setHorizontalGroup(
            enter_mark_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enter_mark_panelLayout.createSequentialGroup()
                .addGroup(enter_mark_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enter_mark_panelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel5))
                    .addGroup(enter_mark_panelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(enter_mark_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(enter_mark_panelLayout.createSequentialGroup()
                                .addGroup(enter_mark_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(51, 51, 51)
                                .addGroup(enter_mark_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chem_mark_field)
                                    .addComponent(bio_mark_field)))
                            .addGroup(enter_mark_panelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(51, 51, 51)
                                .addComponent(phy_mark_field, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(enter_mark_panelLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(check_marks_btn)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        enter_mark_panelLayout.setVerticalGroup(
            enter_mark_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enter_mark_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(enter_mark_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(phy_mark_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(enter_mark_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(chem_mark_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(enter_mark_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bio_mark_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(check_marks_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enter_mark_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enter_mark_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rank_submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rank_submit_btnActionPerformed
        check_rank();       
    }//GEN-LAST:event_rank_submit_btnActionPerformed

    private void get_rank_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_rank_fieldActionPerformed
        
    }//GEN-LAST:event_get_rank_fieldActionPerformed

    private void phy_mark_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phy_mark_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phy_mark_fieldActionPerformed

    private void bio_mark_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bio_mark_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bio_mark_fieldActionPerformed

    private void check_marks_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_marks_btnActionPerformed
        check_marks();
    }//GEN-LAST:event_check_marks_btnActionPerformed
    public void check_rank(){
        try{
            String e_rank = get_rank_field.getText();
            System.out.println(e_rank);
            connect();
            String sql = "select entrank from regstudents where u_id = '"+uid+"'";
            rs = stmt.executeQuery(sql);
            rs.next();
            String trank = rs.getString("entrank");
            if(e_rank.equals("")){
               JOptionPane.showMessageDialog(this, "Enter a valid rank", "Warning",JOptionPane.WARNING_MESSAGE);
            }
            else if(e_rank.equals(trank)){
                enter_mark_panel.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Entered rank incorrect", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        catch(Exception e1){
            e1.printStackTrace();
        }
    }
    
    public void check_marks(){
        try{
            int tphy = 0, tchem=0, tbio=0;
            int phy = Integer.parseInt(phy_mark_field.getText());
            int chem = Integer.parseInt(chem_mark_field.getText());
            int bio = Integer.parseInt(bio_mark_field.getText());
            connect();
            String sql1 = "select phy, chem, bio from regstudents where u_id = '"+uid+"'";
            rs = stmt.executeQuery(sql1);
            while(rs.next()){
                tphy = rs.getInt(1);
                tchem = rs.getInt(2);
                tbio = rs.getInt(3);
            }
            if((phy_mark_field.getText().equals(""))||(chem_mark_field.getText().equals(""))||(bio_mark_field.getText().equals(""))){
                JOptionPane.showMessageDialog(this, "Enter a valid mark", "Warning",JOptionPane.WARNING_MESSAGE);
            }
            else if((phy == tphy)&&(chem == tchem)&&(bio==tbio)){
                if(phy>40 && chem>40 && bio >40){
                   String sql2 = "insert into students select * from regstudents where u_id = '"+uid+"'";
                   stmt.executeUpdate(sql2);
                   JOptionPane.showMessageDialog(this, "Qualified for allotment", "Message", JOptionPane.INFORMATION_MESSAGE);
                   this.setVisible(false);
                   this.dispose();
                   }
                else{
                    JOptionPane.showMessageDialog(this, "Sorry! You are not qualified for allotment", "Error", JOptionPane.ERROR_MESSAGE);
                    this.setVisible(false);
                    this.dispose();
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Incorrect mark. Re-enter", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
        catch(SQLException e1){
            e1.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enter_mark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enter_mark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enter_mark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enter_mark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enter_mark().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bio_mark_field;
    private javax.swing.JButton check_marks_btn;
    private javax.swing.JTextField chem_mark_field;
    private javax.swing.JPanel enter_mark_panel;
    private javax.swing.JLabel enter_rank_label;
    private javax.swing.JTextField get_rank_field;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField phy_mark_field;
    private javax.swing.JButton rank_submit_btn;
    // End of variables declaration//GEN-END:variables
}
