/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package counsellingsystem;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Rachna
 */
public class Enter_options extends javax.swing.JFrame {
     Statement stmt;
    ResultSet rs;
    Connection con;
    String uid;
    /**
     * Creates new form Enter_options
     */
    public Enter_options(String s) {
        initComponents();
        uid = s;
    }
    public Enter_options(){
        System.out.println("Enter options");
    }
    public void connect(){ 
    try
	{
            Class.forName("com.mysql.jdbc.Driver"); 
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project1?autoReconnect=true&useSSL=false", "root","rachna");
            stmt = con.createStatement();
	}
	catch(SQLException e1)
	{ 
            e1.printStackTrace();
        }
        catch(ClassNotFoundException e2){
            e2.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        college_list_combobox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        college_list_combobox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        college_list_combobox3 = new javax.swing.JComboBox<>();
        submit_btn = new javax.swing.JButton();
        colleges_list_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(275, 175));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Enter Options", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe Print", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Option 1*  : ");

        college_list_combobox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Option--", "GMCC1", "GMCK1", "GMCK2", "GMCT1", "GMCT2" }));
        college_list_combobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                college_list_combobox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Option 2*  :");

        college_list_combobox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Option--", "GMCC1", "GMCK1", "GMCK2", "GMCT1", "GMCT2" }));
        college_list_combobox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                college_list_combobox2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Option 3    :");

        college_list_combobox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Option--", "NO", "GMCC1", "GMCK1", "GMCK2", "GMCT1", "GMCT2" }));
        college_list_combobox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                college_list_combobox3ActionPerformed(evt);
            }
        });

        submit_btn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        submit_btn.setText("Submit");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        colleges_list_btn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        colleges_list_btn.setText("View College List");
        colleges_list_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colleges_list_btnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("* - Required Field , NO - No Option");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(college_list_combobox1, 0, 112, Short.MAX_VALUE)
                            .addComponent(college_list_combobox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(college_list_combobox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(submit_btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(colleges_list_btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(colleges_list_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(college_list_combobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(college_list_combobox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(college_list_combobox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(submit_btn)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void college_list_combobox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_college_list_combobox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_college_list_combobox3ActionPerformed

    private void college_list_combobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_college_list_combobox1ActionPerformed
       
    }//GEN-LAST:event_college_list_combobox1ActionPerformed

    private void college_list_combobox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_college_list_combobox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_college_list_combobox2ActionPerformed

    private void colleges_list_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colleges_list_btnActionPerformed
       new Colleges_list().setVisible(true);
    }//GEN-LAST:event_colleges_list_btnActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        get_options();
    }//GEN-LAST:event_submit_btnActionPerformed

    public void get_options(){
        //String gmcc1, gmct1, gmct2, gmck1, gmck2;
        String option_one = (String)college_list_combobox1.getSelectedItem();
        String option_two = (String)college_list_combobox2.getSelectedItem();
        String option_three = (String)college_list_combobox3.getSelectedItem();
        if((option_one.equals(""))&&(option_two.equals(""))&&(option_three.equals(""))){
            JOptionPane.showMessageDialog(this, "Enter atleast two options", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if((option_one.equals(option_two))||(option_one.equals(option_three))||(option_two.equals(option_three))){
               JOptionPane.showMessageDialog(this, "Two options cannot be the same", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //if((!option_one.equals("NO"))||((option_two.equals("NO"))&&(option_three.equals("NO")))){
            connect();
            String sql = "insert into options values ('"+uid+"', '"+option_one+"', '"+option_two+"', '"+option_three+"')";
            try{
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Options Entered", "Message", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                this.dispose();
            }
            catch(SQLException e1){
                e1.printStackTrace();
            }
        }
    }
         
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enter_options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enter_options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enter_options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enter_options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enter_options().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> college_list_combobox1;
    private javax.swing.JComboBox<String> college_list_combobox2;
    private javax.swing.JComboBox<String> college_list_combobox3;
    private javax.swing.JButton colleges_list_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submit_btn;
    // End of variables declaration//GEN-END:variables
}
