/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package counsellingsystem;
import database.MySqlConnect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Rachna
 */
public class StudentHome extends javax.swing.JFrame {
    Connection con;
    ResultSet rs ;
    Statement stmt;
    String s;
    /**
     * Creates new form StudentHome
     */
     public void connect(){ 
    try
	{
            Class.forName("com.mysql.jdbc.Driver"); 
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project1?autoReconnect=true&useSSL=false", "root","rachna");
            stmt = con.createStatement();
	}
	catch(SQLException e1)
	{ 
            e1.printStackTrace();
        }
        catch(ClassNotFoundException e2){
            e2.printStackTrace();
        }
    }
    public StudentHome(String username) {
        initComponents();
        try{
             student_home_panel.setVisible(true);
             String sname = "Welcome :  " + username ;
             welcome_label.setText(sname);
             connect();
            stmt = con.createStatement();
             String sql = "select u_id ,dob, sex, age, entrank from regstudents where name='"+ username+"';"; 
             rs = stmt.executeQuery(sql);
             rs.next();
             s = rs.getString(1);
             String su_id = "   User-ID   : " + rs.getString(1);
             u_id_label.setText(su_id);
             String sdob = "Date of birth : " + rs.getString("dob");
             dob_label.setText(sdob);
             String ssex = "     Sex      : " + rs.getString("sex");
             sex_label.setText(ssex);
             String sage = "     Age      : " + rs.getInt("age");
             age_label.setText(sage);
             String erank = "Entrance Rank : " + rs.getString("entrank");
             rank_label.setText(erank);
             
        }
        catch(Exception e1){
            e1.printStackTrace();
        }
    }
    StudentHome(){
        System.out.println("Student page");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_home_panel = new javax.swing.JPanel();
        welcome_label = new javax.swing.JLabel();
        Logout_btn = new javax.swing.JButton();
        marks_btn = new javax.swing.JButton();
        options_btn = new javax.swing.JButton();
        u_id_label = new javax.swing.JLabel();
        dob_label = new javax.swing.JLabel();
        sex_label = new javax.swing.JLabel();
        age_label = new javax.swing.JLabel();
        rank_label = new javax.swing.JLabel();
        allotment_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(250, 150));

        student_home_panel.setBackground(new java.awt.Color(255, 255, 255));
        student_home_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Student Home", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe Print", 0, 14))); // NOI18N
        student_home_panel.setPreferredSize(new java.awt.Dimension(500, 500));

        welcome_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        welcome_label.setText("WELCOME  :  ");

        Logout_btn.setBackground(new java.awt.Color(255, 255, 255));
        Logout_btn.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        Logout_btn.setText("Logout");
        Logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_btnActionPerformed(evt);
            }
        });

        marks_btn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        marks_btn.setText("Enter Marks");
        marks_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks_btnActionPerformed(evt);
            }
        });

        options_btn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        options_btn.setText("Enter Options");
        options_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options_btnActionPerformed(evt);
            }
        });

        u_id_label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        u_id_label.setText("jLabel1");

        dob_label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dob_label.setText("jLabel3");

        sex_label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        sex_label.setText("jLabel5");

        age_label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        age_label.setText("jLabel7");

        rank_label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        rank_label.setText("jLabel9");

        allotment_btn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        allotment_btn.setText("Get Allotment");
        allotment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allotment_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout student_home_panelLayout = new javax.swing.GroupLayout(student_home_panel);
        student_home_panel.setLayout(student_home_panelLayout);
        student_home_panelLayout.setHorizontalGroup(
            student_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student_home_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(student_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(student_home_panelLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(welcome_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(Logout_btn))
                    .addGroup(student_home_panelLayout.createSequentialGroup()
                        .addGroup(student_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(options_btn)
                            .addComponent(allotment_btn)
                            .addComponent(marks_btn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(student_home_panelLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(student_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(u_id_label, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(dob_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sex_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(age_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rank_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        student_home_panelLayout.setVerticalGroup(
            student_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student_home_panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(student_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcome_label)
                    .addComponent(Logout_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(u_id_label)
                .addGap(19, 19, 19)
                .addGroup(student_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marks_btn)
                    .addComponent(dob_label))
                .addGap(26, 26, 26)
                .addGroup(student_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(options_btn)
                    .addComponent(sex_label))
                .addGroup(student_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(student_home_panelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(allotment_btn))
                    .addGroup(student_home_panelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(age_label)))
                .addGap(3, 3, 3)
                .addComponent(rank_label)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(student_home_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(student_home_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed
        new Counseling_system().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_Logout_btnActionPerformed

    private void marks_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks_btnActionPerformed
        try{
            connect();
            String sql = "select * from rank";
            rs = stmt.executeQuery(sql);
            if(!rs.isBeforeFirst()){
                Enter_mark em = new Enter_mark(s);
                em.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Registration is closed", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(SQLException e1){
            e1.printStackTrace();
        }
    }//GEN-LAST:event_marks_btnActionPerformed

    private void options_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_options_btnActionPerformed
        try{
            String sql = "select * from GMCC1";
            rs = stmt.executeQuery(sql);
            if(!rs.isBeforeFirst()){
                Enter_options op = new Enter_options(s);
                op.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "This functionality is closed", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(SQLException e1){
            e1.printStackTrace();
        }
    }//GEN-LAST:event_options_btnActionPerformed

    private void allotment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allotment_btnActionPerformed
        try{ 
         String sql = " select * from rank ";
         rs = stmt.executeQuery(sql);
         if(!rs.isBeforeFirst()){
             new Student_allotment_display().setVisible(false);
         }
         else{
             
             new Student_allotment_display(username.get_username()).setVisible(true);
         }
        }
        catch(SQLException e1){
            e1.printStackTrace();
        }
    }//GEN-LAST:event_allotment_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout_btn;
    private javax.swing.JLabel age_label;
    private javax.swing.JButton allotment_btn;
    private javax.swing.JLabel dob_label;
    private javax.swing.JButton marks_btn;
    private javax.swing.JButton options_btn;
    private javax.swing.JLabel rank_label;
    private javax.swing.JLabel sex_label;
    private javax.swing.JPanel student_home_panel;
    private javax.swing.JLabel u_id_label;
    private javax.swing.JLabel welcome_label;
    // End of variables declaration//GEN-END:variables
}
